### ISSUE TITLE
Is there a way to get the correct Z location?

### ISSUE THREAD

**Issue by NiukNiuk** [manticorp/unrealheightmap#19]
First of all, thanks for your great tool!
I'd like to know if it's possible to also get the correct Z location of a generated area?
Thanks!

**Comment by NiukNiuk** [comment]
Thanks for your reply. Yeah I was meaning the Z location in UE, once your landscape is created (based on its "pivot point").
But I understand that they might be limitations. Thanks anyway, and thank you for your great tool!

**Comment by manticorp** [comment]
No worries! Glad you've enjoyed it, hopefully you'll still be able to make use of it :)

For your purpose, why do you need the landscape itself to be at the correct z location?

I think the limitations come in because UE5 stored height as a 16bit integer/heightfield, so 65536 discrete values.

i.e. If you want a resolution of ~5cm then your maximum height range is about 3,000m.

If you wanted to store, say, a 3000m mountain that was already 10,000m high above sea level at the correct z-height, you would have to give up so much resolution on the z axis that you would have only 20/30cm resolution left over.

You _can_ accomplish what you're after by turning the normalisation value to "Off" which gives absolute values from 0 to 2^15 in m, or a regular normalisation with fixed values of -32513 to +32768.

You'd then have to work out the correct z-scale to get everything working right, but the resolution would be around 5m (I think).

**Comment by NiukNiuk** [comment]
> For your purpose, why do you need the landscape itself to be at the correct z location?

Well it's just for "realistic" purposes. I'm working on 3D restitutions of archaeological locations, and when I work on an area and generate its landscape, it's not that easy to guess the correct real Z location in UE.
For example let's say that I'd like to generate a landscape of a plateau and its top point is at about 700m. Once generated in UE, I'm using orthographic views (left/right) and guides (like a huge 700m high box with its pivot point on zero) to slowly move the landscape on its Z axis until its top point is correctly located.
So yeah having a way to get this Z location easier would have been great but I understand that there might be limitations in the engine.
But anyway your tool is already doing a lot of work by giving us the correct Z scale (it was a mess to guess before that), so that's great :) Thanks again!

**Comment by manticorp** [comment]
Ahh I gotcha - yes I think it would take an extra translation layer to get the physical co-ordinates to match up with the z-heights in UE due to limitations in how UE stores heightmap data.

If it were me I would make a component/blueprint for translating real world coordinates to in game coordinates, and call on that to place objects. You would just need to store a single number, e.g. the lowest z height in your world, to be able to calculate it.

**Comment by NiukNiuk** [comment]
> If it were me I would make a component/blueprint for translating real world coordinates to in game coordinates, and call on that to place objects. You would just need to store a single number, e.g. the lowest z height in your world, to be able to calculate it.
Way too complicated for me :)  but thanks for the idea! 
Your tool is already doing most of the work so that's great!
