### ISSUE TITLE
Bug: horizontal distance and x multiplier is wrong

### ISSUE THREAD

**Issue by teddybee** [manticorp/unrealheightmap#4]
I checked the distance on google maps with a 2017x2017 resolution rectangle. The vertical length in real life is around 26 km and the vertical as well. 
Your horizontal km on the site shows around 35km, and in unreal the terrain is 33.6 km. (you can measure it in top view with mouse middle button).
The x/z multiplier is also miscalculated. 
@47.6549426,18.7965527

**Comment by manticorp** [comment]
Thank you for the information, can you please provide an example? A url and/or screenshot of your settings would be great.I'm currently just using a simple formula that converts the lat/lng bounds to distances, but it may not be quite correct.I couldn't find a reliable source/formula. There are also projection issues that me a even though the image is square the area it represents is a real world rectangle.I suppose you could do an uneven scaling when importing into unreal.

**Comment by teddybee** [comment]
For example with this query
https://manticorp.github.io/unrealheightmap/#latitude/47.47823216312884/longitude/19.15191650390625/zoom/10/outputzoom/13/width/2017/height/2017
The 4-1 length is 26 km, the whole rectangle is 104km
<img width="613" alt="image" src="https://user-images.githubusercontent.com/11610010/228956893-72850d19-a04d-49dd-8e77-e18fea3d85d0.png">

**Comment by manticorp** [comment]
Thank you very much for bringing this up.

This should now be fixed.

## Before:

![before](https://user-images.githubusercontent.com/3750419/229071987-4bb4f536-7427-40c8-b5af-18b65491fd1b.png)

## After:

![after](https://user-images.githubusercontent.com/3750419/229072004-ce523d38-d76d-42eb-a22a-1e715209f11d.png)

In retrospect this should have been obvious because mercator preserves shapes - i.e. a square should project square over small enough distances:

![Tissot_mercator](https://user-images.githubusercontent.com/3750419/229072559-447851c2-f325-47d2-95d5-3e43bbcd063a.png)

So the squares should have been even in width and height.

I have been using this script myself to try and generate 3D printed models of mountainous areas, and realise now all of my calculations have been incorrect - d'oh! I will have to go back and remake them!
